### ISSUE TITLE
Enter and escape in virtual keyboard

### ISSUE THREAD

**Issue by PatrickMassot** [edukera/issues#3]
I don't see a way to use the virtual keyboard to replace hitting the Esc or Enter key of the physical keyboard. Esc is useful to give up finding the correct unknown. Enter can usually be avoided by clicking some button on the main interface, but sometimes the virtual keyboard hides this button.

**Comment by rognierbenoit** [comment]
Thank you Patrick for your feedback.

You are right, when the preview window is overlapped by the virtual keyboard, the Enter button cannot be hit. Indeed a solution is to put this button on the keyboard. 

The escape button is more ambiguous because, when physical escape key is hit, the preview window closes, which closes as a consequence the virtual keyboard. This action is already covered by the cross button in the upper right corner of the preview window. 

Does the action you think of is a "clear field" action ? In which case there could indeed be a "clear field" button on the virtual keyboard.

**Comment by PatrickMassot** [comment]
There are cases where the virtual keyboard appears without the preview window, when unknowns are entered directly on the main window, especially if you miss an opportunity to choose unknowns in the preview window. I just tried to reproduce this in a random exercise:

![eduk](https://cloud.githubusercontent.com/assets/14060883/26029988/422de3e2-3844-11e7-8f48-e8debab3cdb0.png)


The clear field action is also a good idea (but not what I was discussing).

**Comment by rognierbenoit** [comment]
Thank you for the clarification. We refer to this instantiation mode as "in situ".

Indeed when instantiating in situ, there could be a cross button in the upper right corner of the virtual keyboard. We will add that for next release end of may.

**Comment by rognierbenoit** [comment]
The virtual keyboard for in situ instantiation now has a close button in the upper right corner : 


<img width="762" alt="screen shot 2017-05-15 at 20 15 30" src="https://cloud.githubusercontent.com/assets/4006868/26072338/6ab04bf8-39ab-11e7-9af4-6fa823a4641e.png">
