### ISSUE TITLE
[enhancement] Exercices selection in classes

### ISSUE THREAD

**Issue by PatrickMassot** [edukera/issues#7]
Currently it seems classes creators can only select whole chapters. It would be nice to get finer grained control on the list of exercises available to students.

**Comment by rognierbenoit** [comment]
This feature has been required by several professors, so it really makes sense.

We plan to add by September the possibility to set the following properties for each exercise : 
* visible : if on, the student can see and solve the exercise
* scorable (when visible=true) :  the professor can filter activity reports on scorable exercises ( typically in order to score students on)

In the future, there will also be the possibility to select a set of exercises for an exam/assessment session.

**Comment by rognierbenoit** [comment]
It is now available is current version.
